CREATE TABLE [dbo].[Branches](
	[BranchId]				INT			 NOT NULL PRIMARY KEY IDENTITY(1, 1),
	[CompanyId]				INT			 NOT NULL,
	[BranchName]			VARCHAR(150) NOT NULL,
	[BranchType]			VARCHAR(2)   NULL,
	[BranchVoucherNoPrefix] VARCHAR(5)   NULL,
	[Address]				VARCHAR(250) NOT NULL,
	[Mobile]				VARCHAR(15)  NULL,
	[OtherMobile]			VARCHAR(15)  NULL,
	[PhoneNo]				VARCHAR(50)  NULL,
	[CityId]				INT			 NOT NULL,
	[StateId]				INT			 NULL,
	[GSTNo]					VARCHAR(30)  NULL,
	[OutwardRateType]		CHAR(1)		 NULL,
	[FromCustCardNo]		INT			 NOT NULL,
	[ToCustCardNo]			INT			 NOT NULL,
	[BranchAccountId]		INT			 NULL,
	[HOAccountId]			INT			 NULL,
	[AllowedBankAccountId]	VARCHAR(200) NULL,
	[AllowedCardAccountId]	VARCHAR(200) NULL,
	[AllowedBankDaybookId]	VARCHAR(150) NULL,
	[AllowedCompanyId]		VARCHAR(120) NOT NULL,
	[StockOutwardAccountId] INT		     NULL,
	[StockInwardAccountId]	INT		     NULL,
	[TaxPayerTypeId]		INT		     NOT NULL,
	[IsActive]				BIT			 NOT NULL DEFAULT 1,
	[CreatedBy]				INT			 NOT NULL,
	[CreatedDate]			DATETIME	 NOT NULL,
	[UpdatedBy]				INT			 NULL,
	[UpdatedDate]			DATETIME	 NULL,
	[BranchTransferd]		BIT			 NOT NULL DEFAULT 0,
	[Transfered]			BIT			 NOT NULL DEFAULT 0,
	[ChangeTimeStamp]		ROWVERSION	 NOT NULL,
)