CREATE TABLE [dbo].[Companies](
	[CompanyId]			   INT			NOT NULL PRIMARY KEY IDENTITY(1, 1),
	[CompanyName]		   VARCHAR(100) NOT NULL,
	[SubCompanyName]	   VARCHAR(100) NOT NULL,
	[ShortName]			   VARCHAR(10)	NOT NULL,
	[BusinessTypeId]	   INT			NULL,
	[Address]			   VARCHAR(250) NOT NULL,
	[CityId]			   INT			NOT NULL,
	[StateId]			   INT			NULL,
	[Pincode]			   VARCHAR(10)  NOT NULL,
	[PhoneNo]			   VARCHAR(30)  NOT NULL,
	[MobileNo]			   VARCHAR(15)  NULL,
	[EmailId]			   VARCHAR(125) NOT NULL,
	[WebSite]			   VARCHAR(60)  NULL,
	[GSTNo]				   VARCHAR(50)  NULL,
	[PANNO]				   VARCHAR(30)  NOT NULL,
	[JurisDiction]		   VARCHAR(150) NULL,
	[CurrentBranchId]	   INT			NULL,
	[WithOutBarcodeOption] BIT		    NOT NULL,
	[CompositionScheme]	   BIT			NOT NULL,
	[TaxPayerTypeId]	   CHAR(1)		NULL,
	[CompanyTypeId]	       INT			NULL,
	[IsActive]			   BIT			NOT NULL DEFAULT 1,
	[CreatedBy]			   INT			NOT NULL,
	[CreatedDate]		   DATETIME		NOT NULL,
	[UpdatedBy]			   INT			NULL,
	[UpdatedDate]		   DATETIME		NULL,
	[BranchTransferd]	   BIT			NOT NULL DEFAULT 0,
	[Transfered]		   BIT			NOT NULL DEFAULT 0,
	[ChangeTimeStamp]	   ROWVERSION	NOT NULL,
)