CREATE TABLE [dbo].[AccountGroups](
	[GroupId]				  INT			NOT NULL PRIMARY KEY IDENTITY(1, 1),
	[GroupIdManual]			  INT           NOT NULL,
	[GroupTypeId]			  INT			NOT NULL,
	[GroupName]				  VARCHAR(120)  NOT NULL,
	[AccountTransferToBranch] BIT		    NOT NULL,
	[IsActive]				  BIT			NOT NULL DEFAULT 1,
	[CreatedBy]				  INT			NOT NULL,
	[CreatedDate]			  DATETIME		NOT NULL,
	[UpdatedBy]				  INT			NULL,
	[UpdatedDate]			  DATETIME		NULL,
	[BranchTransferd]		  BIT			NOT NULL DEFAULT 0,
	[Transfered]			  BIT			NOT NULL DEFAULT 0,
	[ChangeTimeStamp]		  ROWVERSION	NOT NULL,
)