CREATE TABLE [dbo].[DesignNos](
	[DesignNoId]		INT			 NOT NULL PRIMARY KEY IDENTITY(1, 1),
	[CompanyId]			INT			 NOT NULL,
	[BranchId]			INT			 NOT NULL,
	[DesignNo]			VARCHAR(100) NOT NULL,
	[ItemId]			INT			 NULL,
	[PurchaseRate]		FLOAT		 NULL,
	[SalesRate]			FLOAT		 NULL,
	[MRP]				FLOAT		 NULL,
	[WhSalesRate]		FLOAT		 NULL,
	[WhSalesRate2]		FLOAT		 NULL,
	[MinStockQty]		FLOAT		 NULL,
	[MaxStockQty]		FLOAT		 NULL,
	[Remarks]			VARCHAR(200) NULL,
	[IsActive]			BIT			 NOT NULL DEFAULT 1,
	[CreatedBy]			INT			 NOT NULL,
	[CreatedDate]		DATETIME	 NOT NULL,
	[UpdatedBy]			INT			 NULL,
	[UpdatedDate]		DATETIME	 NULL,
	[BranchTransferd]	BIT			 NOT NULL DEFAULT 0,
	[Transfered]		BIT			 NOT NULL DEFAULT 0,
	[ChangeTimeStamp]	ROWVERSION   NOT NULL,
)