CREATE TABLE [dbo].[Employees](
	[EmployeeId]		INT			 NOT NULL PRIMARY KEY IDENTITY(1, 1),
	[CompanyId]			INT			 NOT NULL,
	[BranchId]			INT			 NOT NULL,
	[FirstName]			VARCHAR(120) NOT NULL,
	[MiddleName]		VARCHAR(120) NULL,
	[LastName]			VARCHAR(120) NULL,
	[ShortName]			VARCHAR(25)  NOT NULL,
	[EmployeeCode]		VARCHAR(20)  NULL,
	[DepartmentId]		INT			 NULL,
	[DesignationId]		INT			 NULL,
	[AlloweCompanyId]	VARCHAR(120) NULL,
	[AllowedBranchId]	VARCHAR(120) NULL,
	[Address1]			VARCHAR(150) NULL,
	[Address2]			VARCHAR(150) NULL,
	[Address3]			VARCHAR(150) NULL,
	[CityId]			INT			 NULL,
	[StateId]			INT			 NULL,
	[PinCode]			VARCHAR(10)  NULL,
	[MobileNo]			VARCHAR(15)  NULL,
	[PhoneNo]			VARCHAR(30)  NULL,
	[AdharCardNo]		VARCHAR(20)  NULL,
	[GenderId]			INT			 NULL,
	[EmailId]			VARCHAR(120) NULL,
	[BirthDate]			DATETIME	 NULL,
	[JoinDate]			DATETIME	 NOT NULL,
	[ResignDate]		DATETIME	 NULL,
	[WeekoffDay]		INT			 NULL,
	[Salary]			FLOAT		 NOT NULL,
	[InTime]			TIME(7)		 NULL,
	[OutTime]			TIME(7)		 NULL,
	[AccountId]			INT			 NULL,
	[CommissionOn]		VARCHAR(1)   NULL,
	[CommisionPrc]		FLOAT		 NOT NULL,
	[IsActive]			BIT			 NOT NULL DEFAULT 1,
	[CreatedBy]			INT			 NOT NULL,
	[CreatedDate]		DATETIME	 NOT NULL,
	[UpdatedBy]			INT			 NULL,
	[UpdatedDate]		DATETIME	 NULL,
	[BranchTransferd]	BIT			 NOT NULL DEFAULT 0,
	[ChangeTimeStamp]	ROWVERSION	 NOT NULL,
)