CREATE TABLE [dbo].[GlobalSettings](
	[GlobalSettingId]		INT			 NOT NULL PRIMARY KEY IDENTITY(1, 1),
	[SiteName]				VARCHAR(120) NOT NULL,
	[CurrentSiteUrl]		VARCHAR(500) NOT NULL,
	[Logo]					NVARCHAR(MAX) NULL,
	[Favicon]				NVARCHAR(MAX) NULL,
	[SiteTagLine]			VARCHAR(500) NULL,
	[SiteFooter]			VARCHAR(200) NULL,
	[ReceivedOnEmail]		VARCHAR(500) NOT NULL,
	[SendFromEmail]			VARCHAR(500) NOT NULL,
	[SMTP]					VARCHAR(500) NULL,
	[Password]				VARCHAR(500) NULL,
	[Port]					VARCHAR(50)  NULL,
	[SSL]					BIT			 NOT NULL,
	[PathToFolder]			VARCHAR(500) NULL,
	[ListLimit]				INT			 NOT NULL DEFAULT 10,
	[IsActive]				BIT			 NOT NULL DEFAULT 1,
	[CreatedBy]				INT			 NOT NULL,
	[CreatedDate]			DATETIME	 NOT NULL,
	[UpdatedBy]				INT			 NULL,
	[UpdatedDate]			DATETIME	 NULL,
	[ChangeTimeStamp]		ROWVERSION   NOT NULL,
)