CREATE TABLE [dbo].[HSNTaxes](
	[HSNTaxId]          INT			NOT NULL PRIMARY KEY IDENTITY(1, 1),
	[HSNCodeId]         INT			NOT NULL,
	[TaxId]		        INT			NOT NULL,
	[FromDate]          DATETIME	NOT NULL,
	[ToDate]            DATETIME	NOT NULL,
	[FromRate]          FLOAT		NOT NULL,
	[ToRate]            FLOAT		NOT NULL,
	[FromPurcRate]      FLOAT		NOT NULL,
	[ToPurcRate]        FLOAT		NOT NULL,
	[IsActive]			BIT			NOT NULL DEFAULT 1,
	[CreatedBy]			INT			NOT NULL,
	[CreatedDate]		DATETIME	NOT NULL,
	[UpdatedBy]			INT			NULL,
	[UpdatedDate]		DATETIME	NULL,
	[BranchTransferd]	BIT			NOT NULL DEFAULT 0,
	[Transfered]		BIT			NOT NULL DEFAULT 0,
	[ChangeTimeStamp]	ROWVERSION	NOT NULL,
)