CREATE TABLE [dbo].[Items](
	[ItemId]		  INT NOT NULL PRIMARY KEY IDENTITY(1, 1),
	[CompanyId]       INT          NOT NULL,
	[BranchId]	      INT          NULL,
	[DepartmentId]    INT          NOT NULL,
	[BrandId]         INT          NOT NULL,
	[ProductId]       INT          NOT NULL,
	[StyleId]         INT          NOT NULL,
	[GroupId]         INT          NULL,
	[ItemName]        VARCHAR(120) NOT NULL,	
	[ShortName]       VARCHAR(40)  NOT NULL,
	[BarcodeType]     CHAR(1)	   NOT NULL,
	[ItemShortcut]    VARCHAR(3)   NULL,
	[DefaultQty]      FLOAT		   NOT NULL,
	[HSNCode]	      VARCHAR(25)  NULL,
	[DayBookType]     CHAR(1)      NULL,
	[ItemWiseMargin]  BIT		   NULL,
	[IsActive]        BIT		   NOT NULL DEFAULT 1,
	[CreatedBy]       INT		   NOT NULL,
	[CreatedDate]     DATETIME     NOT NULL,
	[UpdatedBy]       INT		   NULL,
	[UpdatedDate]     DATETIME	   NULL,
	[BranchTransferd] BIT		   NOT NULL DEFAULT 0,
	[Transfered]      BIT		   NOT NULL DEFAULT 0,
	[ChangeTimeStamp] ROWVERSION   NOT NULL,
)