CREATE TABLE [dbo].[Products](
	[ProductId]			INT			 NOT NULL PRIMARY KEY IDENTITY(1, 1),
	[ProductName]		VARCHAR(100) NOT NULL,
	[ShortName]			VARCHAR(50)  NULL,
	[SizeGroupId]		VARCHAR(200) NULL,
	[MeasurementTypeId] INT			 NOT NULL,
	[IsActive]			BIT			 NOT NULL DEFAULT 1,
	[CreatedBy]			INT			 NOT NULL,
	[CreatedDate]		DATETIME	 NOT NULL,
	[UpdatedBy]			INT			 NULL,
	[UpdatedDate]		DATETIME	 NULL,
	[BranchTransferd]	BIT			 NOT NULL DEFAULT 0,
	[Transfered]		BIT			 NOT NULL DEFAULT 0,
	[ChangeTimeStamp]	ROWVERSION   NOT NULL,
)