CREATE TABLE [dbo].[TaxAccounts](
	CompanyId		        INT NOT NULL,
	TaxId			        INT NOT NULL,
	SGSTInPutAccountId      INT NULL,
	CGSTInPutAccountId      INT NULL,
	IGSTInPutAccountId      INT NULL,
	SGSTOutPutAccountId     INT NULL,
	CGSTOutPutAccountId     INT NULL,
	IGSTOutPutAccountId     INT NULL,
	SGSTPayableAccountId    INT NULL,
	CGSTPayableAccountId    INT NULL,
	IGSTPayableAccountId    INT NULL,
	RCMSGSTPayableAccountId INT NULL,
	RCMCGSTPayableAccountId INT NULL,
	RCMIGSTPayableAccountId INT NULL,
	RCMInPutSGSTAccountId   INT NULL,
	RCMInPutCGSTAccountId   INT NULL,
	RCMInPutIGSTAccountId   INT NULL,
	RCMOutPutSGSTAccountId  INT NULL,
	RCMOutPutCGSTAccountId  INT NULL,
	RCMOutPutIGSTAccountId  INT NULL,
)