CREATE TABLE [dbo].[Taxes](
	[TaxId]			    INT			NOT NULL PRIMARY KEY IDENTITY(1, 1),
	[TaxTypeId]			INT			NOT NULL,
	[TaxName]			VARCHAR(50) NOT NULL,
	[SGSTPrc]			FLOAT		NOT NULL,
	[CGSTPrc]			FLOAT		NULL,
	[IGSTPrc]			FLOAT		NULL,
	[SurchargePrc]		FLOAT		NOT NULL,
	[IsActive]			BIT			NOT NULL DEFAULT 1,
	[CreatedBy]			INT			NOT NULL,
	[CreatedDate]		DATETIME	NOT NULL,
	[UpdatedBy]			INT			NULL,
	[UpdatedDate]		DATETIME	NULL,
	[BranchTransferd]	BIT			NOT NULL DEFAULT 0,
	[Transfered]		BIT			NOT NULL DEFAULT 0,
	[ChangeTimeStamp]	ROWVERSION	NOT NULL,
)